`site-policyページ`：実装 #140
kougakusai/kougakusai-hp2022 pull request #146
Opened 2022-10-06 04:34 UTC by minusvoid

`サイトポリシーページ`のデザインを参考
リンクは`indexページ`の`footer`からのみ。

2022-10-06 14:34 UTC, fujitargz approved these changes
LGTM

2022-10-08 05:30 UTC, fujitargz requested changes
#151 でリンクの取り消し線は削除したので`<del>`は使わない方針です。

2022-10-08 05:44 UTC, minusvoid commented
`Footer`の未使用リンクの`del`部分は削除しました。

2022-10-08 05:51 UTC, fujitargz approved these changes
LGTM

欲を言うなら revert した方がコミット履歴を見て意味が分かりやすかったかな、と思います。（revert でどうなるか深く確認していないので本当に revert が適切かどうかは確認できていませんが、そういう手段もあるということで）

2022-10-08 05:51 UTC, merged