ホームボタン実装 #5
kougakusai/kougakusai-hp2022 pull request #38
Opened 2022-09-09 10:09 UTC by minusvoid

ホームボタンを実装

- `button`要素が一番外側
- 画像は`next/image`で読み込み
- `next/router`で遷移
- `button`のプロパティは全部受けとる

### `next/link`ではなく`button`で実装した理由

`next/link`（以下Link）のa11yのために挿入する子要素`a`が高さを制御できない、かつ要素位置が画像から下側にはみ出て移動できないので、見た目や動作が他コンポーネントへ影響すると予想するから。
`Link`を`button`で代替しても、動作や見た目がほぼ変わらないから。

2022-09-09 11:08 UTC, fujitargz requested changes
`next/link`不採用の件、承知です。
調査などありがとうございます！この方針で問題ないと思います。

2022-09-09 11:08 UTC, fujitargz commented on src/components/Button/HomeButton/HomeButton.tsx
> +      title={title || 'ホーム'}
ホームボタンは汎用性がないので、`title`は固定しちゃって良い気がします。

2022-09-09 11:08 UTC, fujitargz commented on src/components/Button/HomeButton/HomeButton.tsx
> +import { ComponentPropsWithoutRef, MouseEvent, MouseEventHandler } from 'react';
使っていないものが残っちゃってますかね？
（`import`を整理するやつを入れていないので今回は気を遣っていただかないといけないんです、すみません...
そこまで神経質になる必要はありませんが、今回は他の修正もあるのでついでに直しちゃっていただけるとありがたいです。）

2022-09-10 05:25 UTC, fujitargz requested changes
コードに問題はないんですが、追加で修正が必要になってしまったので対応をお願いします...

1. `title`固定化は不要です。
私がナンセンスでした。`title`はもともと`button`の`props`に入っていたんですね...
title固定化の差分は戻していただきたいです。
2. PC版のデザインも出ているので、そちらの対応もお願いします。
サイズが大きくなるみたいです。

どちらも指示間違い&不足で申し訳ありません...

2022-09-10 06:23 UTC, minusvoid commented
ロゴ画像の解像度がモバイル用なので、Figmaから拾って適用しても良いですか？（Figmaのは306^2）

2022-09-10 06:27 UTC, fujitargz commented
> ロゴ画像の解像度がモバイル用なので、Figmaから拾って適用しても良いですか？（Figmaのは306^2）

（解像度とかよく分からないので画像を2枚用意すべきかどうかについては分からないのでお任せしますが、2枚用意する場合は）その方法でOKです。
もともとある画像のファイル名も適宜変更していただいて問題ありません。

2022-09-10 08:20 UTC, fujitargz commented on src/components/Button/HomeButton/HomeButton.tsx
> +      title={title || 'ホーム'}
（嘘でした、この書き方で問題なし）

2022-09-10 08:28 UTC, fujitargz requested changes
画像の拡張子変更を`src/stories/images.stories.tsx`の`import`にも反映しないとエラーで Storybook が起動できません。お手数ですがそちらの対応もお願いします。

カスタムフックは問題なさそうです！

2022-09-10 08:28 UTC, fujitargz commented on src/components/Button/HomeButton/HomeButton.tsx
> +const breakPoint = 1000;
breakpoint は本当に`1000`でしょうか？
TailwindCSS の`sm`に対応させる、とのことだったので値が違う気がします...

https://tailwindcss.com/docs/responsive-design

2022-09-10 10:40 UTC, minusvoid commented on src/components/Button/HomeButton/HomeButton.tsx
> +const breakPoint = 1000;
`sm`に対応させる話を確認しそびれていました。

2022-09-10 10:52 UTC, fujitargz approved these changes
LGTM
ありがとうございました！

2022-09-10 11:05 UTC, fujitargz commented
あ、LGTMじゃないかもしれない
breakpointって`lg`だっけ...？
`sm`より小さい画面はモバイルで`sm`を超えたらPC、では...？

それと、TailwindCSS の`sm`は`640px`以上の場合に適用なので、`max-width`で書くなら`639px`になるかも...？
（`639px`以下の場合に適用、にしないと境界条件が合わない）

2022-09-10 11:35 UTC, fujitargz commented
```js
window.matchMedia('max-width:640px')
```
だと、`640px`**以下**のとき`true`で`640px`**より大きい**のとき`false`になるみたいですね。
したがって breakpoint の数字は`639px`になりそうです。

https://developer.mozilla.org/ja/docs/Web/API/MediaQueryList#%E4%BE%8B

2022-09-10 12:23 UTC, minusvoid commented
`breakpoint`の値を640->639へ変更と、`<Image>`のサイズを直書きにしました（変数にしてたのが2か所のみだったので）

2022-09-10 13:12 UTC, fujitargz approved these changes
正真正銘LGTMですね…お疲れ様でした…！！

2022-09-11 10:23 UTC, merged