メニューボタンの実装
kougakusai/kougakusai-hp2022 pull request #39
Opened 2022-09-10 04:06 UTC by ayagifc

メニューボタンのコンポーネントを作成しました。
画像は背景がついていたため、透過できませんでした。

2022-09-10 05:50 UTC, fujitargz requested changes
爆速対応ありがとうございます～
いくつか気になった点があったので指摘しております。
また、PC版のデザインにも対応していただけると助かります（大きさが変わります）。

2022-09-10 05:50 UTC, fujitargz commented on src/components/Button/MenuButton/MenuButton.tsx
> +import menuIcon from '../../../../public/rhino_soldering.png';
どこにも書いていないし言っていなかったのですが、`public/`から`import`するときは`@public/`と書けるように設定しているので活用してみてください！

今回なら`import menuIcon from '@public/rhino_soldering.png'`と書いても問題なく動作すると思います。

2022-09-10 05:50 UTC, fujitargz commented on src/components/Button/MenuButton/MenuButton.tsx
> +}
引数の型定義は`ComponentPropsWithoutRef<'button'>`にしてみてください。

上記の型は`<button>`の引数の型定義です。
今回の`MenuButton`は Atomic Design でいうところの Atom に相当する汎用的なコンポーネントなので、`<button>`と同様に扱えるようになっていると便利なので、そのような型定義をすると良いです。
（例えば、メニューを実装していないうちは`disabled`を使いたい、と思った場合でも`<button>`と同様に定義していれば問題なく使えるはずです）

#38 が同様の実装をしているので参考にしてみてください！

（型定義の件は Issue にはっきり書いていませんでしたね、申し訳ないです...）

2022-09-10 05:50 UTC, fujitargz commented on src/components/Button/MenuButton/MenuButton.tsx
> +      }}
今回はスタイリングに TailwindCSS を使用しているので、統一のため`style`ではなく`className`に TailwindCSS のクラス名を書く方針でお願いします。

2022-09-10 06:28 UTC, fujitargz commented on src/components/Button/MenuButton/MenuButton.tsx
> +import menuIcon from '../../../../public/rhino_soldering.png';
追記：WikiのTipsに書いてありました（書いてあるとは言っていなかったので知らないはず）。

2022-09-10 06:38 UTC, minusvoid commented
透過版の画像
https://drive.google.com/file/d/1yiymvI3UB82IlXF1OfDWmTa1nuhJ32MT/view?usp=sharing

2022-09-11 01:43 UTC, fujitargz requested changes
良い感じになってきましたー
あと少しだけ修正をお願いします。

2022-09-11 01:43 UTC, fujitargz commented on src/components/Button/MenuButton/MenuButton.tsx
> +}
`extend`する必要ってありますかね...？

`onClick`も`className`も`ComponentPropsWithoutRef<'button'>`にもともと含まれていて、かつその型定義で問題ないと思います。

例えば、今回`extend`した型定義だと`onClick`は引数を受け取らないので、
```js
onClick={(e) =>{
  e.preventDefault();
  // 何か処理...
}}
```
のような操作がしたくなってもできませんし、
`onClick`と`className`が`optional`ではなく必須なので、使わない時でも空の関数や空文字列を渡す必要があります。

逆に言うと、そのような意図があるのであればこの`extend`は適切だと思います。
今回はそのような制約は不要かと思いますので`extend`する必要は無さそうです。

2022-09-11 01:43 UTC, fujitargz commented on src/components/Button/MenuButton/MenuButton.tsx
> +      onClick={onClick}
補足ですが、この実装のように`onClick`をそのまま渡すだけであれば省略可能ですね。
引数のところで`onClick`を destructuring しなければ`restProps`に入ってよしなに扱われるはずです。
（`HomeButton`の実装では引数の`onClick`を実行する前に特定の処理を挟む必要があったためわざわざ destructuring していました）

2022-09-11 04:16 UTC, ayagifc commented on src/components/Button/MenuButton/MenuButton.tsx
> +}
今回extendした型定義でonClickが引数を受け取らないのは知りませんでした。

最初のレビューでいただいたコメントでいっているのは、interfaceでわざわざやる必要なく、関数にComponentPropsWithoutRef<'button'>を付ければいいよということでしょうか？

2022-09-11 04:37 UTC, fujitargz commented on src/components/Button/MenuButton/MenuButton.tsx
> +}
> interfaceでわざわざやる必要なく、関数にComponentPropsWithoutRef<'button'>を付ければいい

はい。そうです。
(コメントする場所がイマイチでしたね、失礼しました)

2022-09-11 07:29 UTC, fujitargz reviewed
(余計な`console.log`が残ってますよ…それだけ消せば完璧…)

2022-09-11 07:39 UTC, fujitargz approved these changes
LGTM！
ありがとうございました。

2022-09-11 10:15 UTC, ujimattya commented
分かりにくくてすみません。メニューボタンには微妙にドロップシャドウついてます。
drop-shadow-sm
をボタンにつけるだけでいいです。

2022-09-11 12:16 UTC, merged