Smallの実装 #21
kougakusai/kougakusai-hp2022 pull request #64
Opened 2022-09-16 09:07 UTC by ga11o

Close #21 
Headingを参考にしました

2022-09-17 04:42 UTC, fujitargz requested changes
サクサク進めていただいてありがとうございます！

コミットメッセージについて、コンポーネントを実装したコミットは Issue 名をそのまま使っても良いと思いますが、それ以外のコミット（`line-height`の修正など）では作業内容について書いていただけると（差分の内容がぱっと見で分かるので）助かります。

2022-09-17 04:42 UTC, fujitargz commented on src/components/Typography/Small/Small.tsx
> +      'font-[Roboto] text-[0.75rem] font-bold leading-[0.875rem] text-[#18283f]',
`font-weight: 400;`なので`font-bold`ではなく`font-normal`ではないでしょうか？

2022-09-17 07:50 UTC, ga11o commented
コミットメッセージについて承知いたしました。
`font-bond`から`font-normal`へ変更しました。

2022-09-17 10:35 UTC, fujitargz approved these changes
LGTM

2022-09-19 12:50 UTC, ujimattya commented
@ga11o 
コンフリクトしてるみたいです。内容はokなので、解消され次第mergeします。

2022-09-20 10:38 UTC, merged